### PR TITLE
Add RedactingWriterSink class to lager for log filtering

### PR DESCRIPTION
**Pull request by julian-hj**
We created this class as a way to automatically scrub through the output of lager logs and make sure that log output doesn't contain any values with key names containing pwd or password.  We also scrub out any string values that contain amazon keys, private keys, etc.

Regular expressions that match patterns in json keys and values can also be overridden when creating a new writer sink, for processes that may handle different kinds of secrets.

We thought it would be a good idea to PR this back to lager, as it seems generally useful.  If you agree, please let us know and we can add some documentation to the PR.

### CODE REVIEW

**Comment by ematpl** [comment]
Thanks, @julian-hj. Is the Persi team or any other CF project actually using this sink?

Best,
Eric

**Comment by julian-hj** [comment]
@ematpl -- hey, sorry for some reason email notification failed to make it into my email.  Yes, we use this sink from the nfsbroker and driver in order to redact passwords from volume service bindings.

**Comment by ematpl** [comment]
Thanks for the update, @julian-hj. We'll prioritize for a Diego pair to review, and we may want to cross-team pair if there are changes or refactors. One Golang stylistic point: "JSON" should remain all-caps, instead of the title-case "Json", since it's an initialism (for example, see https://golang.org/pkg/encoding/json/#RawMessage.MarshalJSON and the "HTTP" in the "ServeHTTP" method on the handler interface, https://golang.org/pkg/net/http/#Handler).

Best,
Eric

**Comment by julian-hj** [comment]
In the javascript world, initialisms and acronyms are camel cased, which imo improves readability especially in cases where you're sticking them together (e.g. XMLHTMLConverter is lots less readable than XmlHtmlConverter.)  Also requiring all UC initialisms seems fairly imprudent in a language where initial uppercase is overloaded to make stuff public.  Having said all that, I can see that UC acronyms are the convention in golang, so I am fine with following the convention even though I think it's kind of a dumb convention.  When in Rome and all that..

**Comment by crhino** [comment]
@julian-hj Reviewed the code. Looks good to us, thought about deduping the WriterSink implementations, but couldn't quite think of a way to merge the two without adding additional complexity.

If you could change the `Json` references (type and constructor) in `json_redactor.go` file to all-caps `JSON`, we will merge it in.

**Comment by julian-hj** [comment]
@crhino: thanks, will do!

**Comment by julian-hj** [comment]
I'll add some brief docs to the readme also.

**Comment by julian-hj** [comment]
On second thought, the README docs don't cover details for any of the other sinks, so it feels a bit odd to put arcana in there about RedactingWriterSink.  We might consider adding a separate breakout doc that goes into the details of the various sink implementations, but otherwise I think it is better to leave the redacting sink undocumented than it is to compromise the nice simple instructions in the current README.

I have updated the names to replace Json with JSON.  Let me know if you want any other changes.

Cheers,
-Julian

**Pull request closed without merging**
